  
export const CREATE_CHART_REQUEST = 'CHART_LIST_REQUEST'
export const CREATE_CHART_SUCCESS = 'CREATE_CHART_SUCCESS'
export const CREATE_CHART_FAIL = 'CREATE_CHART_FAIL'

export const CHART_LIST_REQUEST = 'CHART_LIST_REQUEST'
export const CHART_LIST_SUCCESS = 'CHART_LIST_SUCCESS'
export const CHART_LIST_FAIL = 'CHART_LIST_FAIL'